// 从 shared/invoice-core.ts（唯一人工维护的业务源）生成两端产物：
//   1. miniprogram/utils/invoice.ts     —— 小程序消费的 TS 模块（生成文件，禁止手工修改）
//   2. 共享 HTML 的 INVOICE-CORE 标记块  —— 浏览器 IIFE（生成块，禁止手工修改）
// 用法：
//   npm run build:shared      重新生成并写回
//   npm run check:generated   重新生成并与当前文件比对，不一致则退出码 1（CI 检测产物过期）
import fs from 'node:fs'
import path from 'node:path'
import ts from 'typescript'

const projectRoot = process.cwd()
const corePath = path.join(projectRoot, 'shared', 'invoice-core.ts')
const mpTargetPath = path.join(projectRoot, 'miniprogram', 'utils', 'invoice.ts')
const htmlPath = path.join(projectRoot, 'VBSE发票小程序（2.2版).html')

const GEN_HEADER =
  '// 本文件由 tools/build-shared.mjs 从 shared/invoice-core.ts 自动生成——禁止手工修改。\n' +
  '// 业务源：shared/invoice-core.ts；重新生成：npm run build:shared；过期检测：npm run check:generated\n\n'
const MARKER_BEGIN =
  '// ===== INVOICE-CORE:BEGIN (generated by tools/build-shared.mjs — 禁止手工修改；业务源在 shared/invoice-core.ts) ====='
const MARKER_END = '// ===== INVOICE-CORE:END ====='

const check = process.argv.includes('--check')
const problems = []
const actions = []

const coreSource = fs.readFileSync(corePath, 'utf8')

// —— 产物 1：小程序 TS 模块（保持 TS 形态，构建期由 build-miniprogram.mjs 转 CommonJS）——
const mpContent = GEN_HEADER + coreSource
if (check) {
  if (!fs.existsSync(mpTargetPath)) problems.push('缺少生成产物: miniprogram/utils/invoice.ts')
  else if (fs.readFileSync(mpTargetPath, 'utf8') !== mpContent)
    problems.push('miniprogram/utils/invoice.ts 过期（shared/invoice-core.ts 已变更）——请运行 npm run build:shared')
} else {
  fs.writeFileSync(mpTargetPath, mpContent, 'utf8')
  actions.push('已生成 miniprogram/utils/invoice.ts')
}

// —— 产物 2：浏览器 IIFE（先文本剥离行首 export，再剥离 TS 类型 + 挂 window.VBSECore）——
// 必须在 transpile 之前剥离 export：TS 对含 export 的源会输出 CommonJS 导出机制
// （Object.defineProperty/exports.X = 赋值），在浏览器里直接 ReferenceError；
// 且多行字面量的 `exports.X = [` 首行无法按行安全过滤。剥离后源无 export，
// interface 等类型由 transpile 整体擦除，输出即纯脚本。
const valueNames = [...coreSource.matchAll(/^export\s+(?:const|function)\s+(\w+)/gm)].map((m) => m[1])
const jsBody = ts
  .transpileModule(coreSource.replace(/^export\s+/gm, ''), {
    compilerOptions: { target: ts.ScriptTarget.ES2019, module: ts.ModuleKind.CommonJS },
  })
  .outputText.replace(/"use strict";\s*/, '')
if (/\bexport\b/.test(jsBody) || /(^|\n)\s*exports\b/.test(jsBody))
  problems.push('浏览器 IIFE 生成异常：仍残留 export/exports 语句')
const iife = `window.VBSECore = (function () {\n${jsBody}\n  return { ${valueNames.join(', ')} };\n})();`

const html = fs.readFileSync(htmlPath, 'utf8')
const beginIdx = html.indexOf(MARKER_BEGIN)
const endIdx = html.indexOf(MARKER_END)
if (beginIdx < 0 || endIdx < 0 || endIdx < beginIdx) {
  problems.push('共享 HTML 缺少 INVOICE-CORE 标记块（应位于主 <script> 起始处）')
} else {
  const existingBlock = html.slice(beginIdx + MARKER_BEGIN.length, endIdx)
  if (check) {
    if (existingBlock.trim() !== iife.trim())
      problems.push('共享 HTML 的 INVOICE-CORE 块过期（shared/invoice-core.ts 已变更）——请运行 npm run build:shared')
  } else {
    const newHtml = html.slice(0, beginIdx + MARKER_BEGIN.length) + '\n' + iife + '\n' + html.slice(endIdx)
    fs.writeFileSync(htmlPath, newHtml, 'utf8')
    actions.push(`已注入共享 HTML 的 INVOICE-CORE 块（${valueNames.length} 个导出）`)
  }
}

if (problems.length > 0) {
  for (const problem of problems) console.error('[build-shared] ' + problem)
  process.exit(1)
}
for (const action of actions) console.log('[build-shared] ' + action)
if (check) console.log('[build-shared] 产物均为最新')
